config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  resources :products, only: %i[ index show ] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :message, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :category, :description, presence: true
  validates :price, :stock, :rating, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :value, presence: true, numericality: { only_integer: true }
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end

  def create
  end

  def delete
  end

  private

  def product_params
    params.require(:product).permit(:name, :category, :description, :stock, :price, :rating)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EYardsale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/edit.html.erb
<h1>Product#edit</h1>
<p>Find me in app/views/product/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products</h1>
<div class="container">
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="row search-form-control form-group">
      <input class="form-control string required col-10" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-secondary col-2">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
</div>
<div class="container">
  <div class="cards">
    <% @products.each do |product| %>
    <div class="card" style="width: 16rem; height: 18rem;">
      <img src="https://cdn.shopify.com/s/files/1/0070/7032/files/camera_56f176e3-ad83-4ff8-82d8-d53d71b6e0fe.jpg?v=1527089512" class="card-img-top" alt="..."/>
    <div class="card-body" style="width: 16rem; height: 8rem;">   
      <h5 class="card-title"><%= product.name %></h5>
      <div class="card-text">
        <p><%= product.price %></p>
        <p><%= product.rating %></p>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to "show more", product_path(product) %>
    </div> 
    </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
  <p><%= @product.category %></p>
  <p><%= @product.description %></p>
  <p><%= @product.stock %></p>
  <p>€<%= @product.price %></p>
  <p><%= @product.rating %></p>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/ratings/delete.html.erb
<h1>Ratings#delete</h1>
<p>Find me in app/views/ratings/delete.html.erb</p>

app/views/ratings/edit.html.erb
<h1>Ratings#edit</h1>
<p>Find me in app/views/ratings/edit.html.erb</p>

app/views/ratings/index.html.erb
<h1>Ratings#index</h1>
<p>Find me in app/views/ratings/index.html.erb</p>

app/views/ratings/show.html.erb
<h1>Ratings#show</h1>
<p>Find me in app/views/ratings/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shopping_carts/create.html.erb
<h1>ShoppingCarts#create</h1>
<p>Find me in app/views/shopping_carts/create.html.erb</p>

app/views/shopping_carts/delete.html.erb
<h1>ShoppingCarts#delete</h1>
<p>Find me in app/views/shopping_carts/delete.html.erb</p>

app/views/shopping_carts/edit.html.erb
<h1>ShoppingCarts#edit</h1>
<p>Find me in app/views/shopping_carts/edit.html.erb</p>

app/views/shopping_carts/index.html.erb
<h1>ShoppingCarts#index</h1>
<p>Find me in app/views/shopping_carts/index.html.erb</p>

app/views/shopping_carts/show.html.erb
<h1>ShoppingCarts#show</h1>
<p>Find me in app/views/shopping_carts/show.html.erb</p>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/delete.html.erb
<h1>Transactions#delete</h1>
<p>Find me in app/views/transactions/delete.html.erb</p>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>